# Generated by Django 3.1.7 on 2021-04-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210331_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='access',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', max_length=10),
        ),
    ]
