# Generated by Django 3.1 on 2020-08-25 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200825_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Other',
            new_name='Examples',
        ),
    ]
