# Generated by Django 3.1 on 2020-08-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200825_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Examples',
            new_name='examples',
        ),
    ]
