# Generated by Django 3.1 on 2020-08-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200827_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
