# Generated by Django 3.1 on 2020-10-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200830_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='access',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', max_length=10),
        ),
    ]
